name: e_commerce
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

#---------------- PACKAGES -----------------#
dependencies:
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_dotenv: ^5.2.1
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.2
  internet_connection_checker: ^3.0.1
  provider: ^6.1.2
  readmore: ^3.0.0
  smooth_page_indicator: ^1.2.0+3
  supabase_flutter: ^2.8.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  #--------------- LOCAL ASSETS -------------#
  assets:
    - assets/images/
    - assets/images/banners/
    - assets/images/products/
    - assets/icons/
    - assets/icons/categories/
    - assets/logos/
    - .env
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
